periodics:
- name: exe-test-infra-label-sync
  cron: "5 */6 * * *"  # Every 6th hour at 5 minutes past the hour
  cluster: kubernetes
  labels:
    app: label-sync
  decorate: true
  spec:
    containers:
    - name: label-sync
      image: gcr.io/k8s-prow/label_sync:v20220330-40eb179576
      command:
      - label_sync
      args:
      - --config=/etc/config/labels.yaml
      - --confirm=true
      - --orgs=opdev
      - --token=/etc/github/oauth
      - --endpoint=http://ghproxy.default.svc.cluster.local
      - --endpoint=https://api.github.com
      - --debug
      volumeMounts:
      - name: oauth
        mountPath: /etc/github
        readOnly: true
      - name: config
        mountPath: /etc/config
        readOnly: true
    volumes:
    - name: oauth
      secret:
        secretName: exe-prow-github-app-oauth-token
    - name: config
      configMap:
        name: exe-prow-github-app-label-config
  annotations:
    description: Runs label_sync to synchronize GitHub repo labels with the label config defined in label_sync/labels.yaml.

presubmits:
- name: pull-test-infra-prow-checkconfig
  decorate: true
  run_if_changed: '^(\.prow|prow/(config|plugins|labels|jobs/.*))\.yaml$'
  spec:
    containers:
    - image: gcr.io/k8s-prow/checkconfig:v20220831-a90f89ba44
      command:
      - checkconfig
      args:
      - --config-path=prow/config.yaml
      - --job-config-path=prow/cluster/jobs
      - --plugin-config=prow/plugins.yaml
      - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)
      - --strict
      - --exclude-warning=mismatched-tide
      - --exclude-warning=non-decorated-jobs
      - --exclude-warning=long-job-names

postsubmits:
# comment to trigger
