apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: deck
  namespace: prow
spec:
  host: prow.apps.eng.opdev.io
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: deck
    weight: 100
  wildcardPolicy: None
