apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"deck","namespace":"prow"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"deck"}}}
  creationTimestamp: "2020-12-10T12:26:11Z"
  name: deck
  namespace: prow
  resourceVersion: "1092840697"
  uid: 7bc9e2d1-204b-4b64-b8d3-758e66c5d0c7
spec:
  clusterIP: 172.30.248.160
  clusterIPs:
  - 172.30.248.160
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: deck
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
