apiVersion: ENC[AES256_GCM,data:dZk=,iv:yaGxruUwDyD/52Bs/EQQMmQ/QKtUkL+ytq6W8edJwtY=,tag:k5tcdzlgJ4i9u08Q6n8E1A==,type:str]
data:
    secret: ENC[AES256_GCM,data:sJQ/XqC9cerTtlinks3LqgwN/uyFlznpcXsW9DaNDep6GfySGiLFRCFLRouc97yrogQpR11lyaTKzxco,iv:Et+7Z7lE9y/2QeaV8SkESf+lu9FY5pFObGNqQRzbpfk=,tag:2ywj4pipgEWpW5tktRccMA==,type:str]
kind: ENC[AES256_GCM,data:+nWLFeG1,iv:sAEFDKVL3D3/BEbz080T2KoQkVyKv/yROjBiEJNepB8=,tag:HaI4Z4EpkMkurVW6O9oFwA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:duYwiZmp2HlZcXG7Zm22Yud8haIWT1pfHnRDw3ZGd5g=,iv:4LfT2mzwFDRMmi19jwIYHXWDW9rJaG52K4TigdHYwZo=,tag:TkYgAhJ7o1E/YkAcV92t0A==,type:str]
    namespace: ENC[AES256_GCM,data:9BvS8g==,iv:IRZSQt2/bZBQFsgVi7iYPle2lvXCkMjQwlbhmrMZaAc=,tag:PDNO5dkP2RGIMGp3eO+iiw==,type:str]
type: ENC[AES256_GCM,data:v7dM9wkC,iv:czHRcGqtaIUTTaPCmjHd/n51J8H4EY03PjjZUhz5j0s=,tag:YraGX1vOKnFV8ca5PBqzrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e0u545qt3jee6tg8zaxrgyvyuctjq9k2mffp4czs5xymm3d7lausaasg5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV2JldzRpQTJyaGlEN1RO
            UUduRGVaVk01emhpaEZtdk16NW81K2JmeEU0ClBLUmtPdnVMV25vUkx0WWxiTk1S
            ZzZwQW56WVl0cDFqVS9MVE41NU10Z1UKLS0tIGZWZE5HbmptOFFZbDhDUis5UlZs
            bmwxSzdhM1JNM0pVTWhXL2FEVDVBNzAKRAdKWc8ixVBboBFNxxTbyc6kNsrhgBjE
            GDzGQo8OFu2pGphumVtQ3DH6rsn7tT3JhiT6L1sF6BE2Q5C2iJhfag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T02:10:59Z"
    mac: ENC[AES256_GCM,data:UCieN/Ox+HQ6lqNQGfcoiDSM1O215/YptGzQjg1nIwi0//zajWmhspOz2lVvsmUQC8IkYFc56sDUElC/blvY5M0+xmVum0cfuG1eyuoUV+9PtLEsgqUmeuaI74I/1mhycKHAuJS+/81cQg5RnySzYYw1ME8FzAW1HGf3a72dVeI=,iv:6jmd9kJdyFYpyVjm8mM6QY6X1a6nQNnfapt0ZA/q6Js=,tag:3lAWBRtyQKBSk/v6F3xZWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
