apiVersion: ENC[AES256_GCM,data:KhA=,iv:Rbg2vVAoko9MeyvdWU+n6Ob21LnkcM3v0bga5yQuA3s=,tag:+JYEJa64+cWmfh+O4zzHJA==,type:str]
data:
    secret: ENC[AES256_GCM,data:DVC4kIfJD30o24Qfmr8Fg1/OEuhCsJzRNTP9kYuY5QuxCzWJ0/62R0geTLLTWzYUEO5LxEJF3H4Ylbo/aZvZGi0KgAu+HCR4ktNqmzJHOoQSAgG7kItUo295P54TeytJAMckcED7p3K5nD64Fb7GKNCaBYkcEbjGFXkERf0tFaOHbvRNtPuYT86u1Qop1wKXvZPGSQemOluSZKBHbIxRqE2BprM7cj7N9BYM9uco8yMEbX3R2CxJrffl5Rg03kF6doqWNz/nXULkGahM/99JPnwqL6XU3zRn5UCrAAkMok3SYN5fbNJpU1Z4EcT6yH1V7u8VzK9hY5yMcb0PkE4ihCRn+KflGgPaAKjRaKQUQWirQYHEVVoYiGs+CxLYsO2oLBqaxiqJIMkCay2B,iv:1gcpSJgzF/J6SuBgmq+OCmc8qi8OxQQNE4XMItCx5LY=,tag:dyFEI1jJtMBcSpZv9Thxcg==,type:str]
kind: ENC[AES256_GCM,data:rfAPBE7S,iv:T0EEcMQk8stL0Alp6zxwPFGgPTxNbRkuA2rjHDbc6GA=,tag:9x1ImXIU/NMsOZVx85j2qA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GzWHjA0VT9krdMVw5cLIUHlRI8tQsZ75lxbn074cFFw=,iv:FKwVa9hz/SS52iKAtdMqqwaC1RwhGt3Xg0u3Tlwsbmo=,tag:hzap2CKtqc+ljSIP5YLFOw==,type:str]
    namespace: ENC[AES256_GCM,data:edBWng==,iv:OHWcv7f+f0Sfjwc9sBaBmpCajOMer5DrbVFJmJmTvjI=,tag:9xPbFgczh+ndRURq3o2Lzw==,type:str]
type: ENC[AES256_GCM,data:XA7pUh8+,iv:MHrhz3835SVAV5cq7RBSSuDg0shoeZAYcTu5KGRIiw8=,tag:r+CE0ZPaorwOBtp91cxC3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e0u545qt3jee6tg8zaxrgyvyuctjq9k2mffp4czs5xymm3d7lausaasg5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N2VXeHFPRGNXZUt0Mk1U
            NFh0Ky9LOUlZbGxpejV0UW1wN05FTHRyNWtJClB0aDk2OUJLd2djOHFJSGNEMWFz
            ZkxOakFBR3kxSnI2WmFpQUR3dHVEVU0KLS0tIHQwTzFWM25TOUt2dk8yem45emhh
            MG5KZmcxaHVva3RCQkZaSlVVQVp6WE0K6fOhEVIMaXq84RRayMo1vnmpwf2QPa2a
            92EKuHsoBinIbfCCBc2zCXMJbmJn1VElUmPojKdJoGK4tdy+VvgjJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T02:10:27Z"
    mac: ENC[AES256_GCM,data:lztoyxXysgxqifOJn5t/58KUGWVa3sU315xRMAB3JbrgLJRc6nB7bsEi2Trr1ET/P8rO9AJ3jtm9y4S7/a8B39Li2petF5tJ0ZWZE4P+yahyxCAF4RG+3Tf6v8Azg54Lb/l19QY8uFQ9TdqF018WaPoc/LaerpUxGieDoIGxhqc=,iv:KKaTYMmVKDSdYg/2K494M3EfGdDLGoEDi/38MSJuqfY=,tag:LvsUQtWSCd9jOm5jec6BSg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
