apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ghproxy"},"name":"ghproxy","namespace":"prow"},"spec":{"ports":[{"name":"main","port":80,"protocol":"TCP","targetPort":8888},{"name":"metrics","port":9090}],"selector":{"app":"ghproxy"},"type":"ClusterIP"}}
  creationTimestamp: "2020-12-10T12:26:11Z"
  labels:
    app: ghproxy
  name: ghproxy
  namespace: prow
  resourceVersion: "1231195"
  uid: 20ee9480-98c0-4a32-bcbe-1538b3786456
spec:
  clusterIP: 172.30.186.173
  clusterIPs:
  - 172.30.186.173
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: main
    port: 80
    protocol: TCP
    targetPort: 8888
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: ghproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
