apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ghproxy
  name: ghproxy
  namespace: prow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ghproxy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ghproxy
    spec:
      containers:
      - args:
        - --cache-dir=/cache
        - --cache-sizeGB=99
        - --push-gateway=pushgateway
        - --serve-metrics=true
        image: gcr.io/k8s-prow/ghproxy:v20220818-6dcd812eb2
        imagePullPolicy: IfNotPresent
        name: ghproxy
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: ghproxy
