apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hook
  namespace: prow
spec:
  host: prow.apps.eng.opdev.io
  path: /hook
  port:
    targetPort: 8888
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hook
    weight: 100
  wildcardPolicy: None
