apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hook","namespace":"prow"},"spec":{"ports":[{"port":8888}],"selector":{"app":"hook"}}}
  creationTimestamp: "2020-12-10T12:26:11Z"
  name: hook
  namespace: prow
  resourceVersion: "1092842146"
  uid: 056f408d-a28c-4bfa-9a1c-2e1d40e85594
spec:
  clusterIP: 172.30.85.142
  clusterIPs:
  - 172.30.85.142
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8888
  selector:
    app: hook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
