apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: horologium
  namespace: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: horologium
subjects:
- kind: ServiceAccount
  name: horologium
