apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"minio","namespace":"prow"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":9000}],"selector":{"app":"minio"},"type":"ClusterIP"}}
  creationTimestamp: "2020-12-10T12:26:11Z"
  name: minio
  namespace: prow
  resourceVersion: "1231200"
  uid: 464186d4-a033-4149-b27b-feb64ea19493
spec:
  clusterIP: 172.30.197.84
  clusterIPs:
  - 172.30.197.84
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
