apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prow-controller-manager
  name: prow-controller-manager
  namespace: prow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prow-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prow-controller-manager
    spec:
      containers:
      - args:
        - --dry-run=false
        - --config-path=/etc/config/config.yaml
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --enable-controller=plank
        - --github-app-id=$(GITHUB_APP_ID)
        - --github-app-private-key-path=/etc/github/cert
        env:
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              key: appid
              name: exe-prow-github-app-github-token
        image: gcr.io/k8s-prow/prow-controller-manager:v20220818-6dcd812eb2
        imagePullPolicy: IfNotPresent
        name: prow-controller-manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/github
          name: github-token
          readOnly: true
        - mountPath: /etc/config
          name: config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prow-controller-manager
      serviceAccountName: prow-controller-manager
      terminationGracePeriodSeconds: 30
      volumes:
      - name: github-token
        secret:
          defaultMode: 420
          secretName: exe-prow-github-app-github-token
      - configMap:
          defaultMode: 420
          name: exe-prow-github-app-config
        name: config
