apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sinker
  namespace: prow
rules:
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  verbs:
  - delete
  - list
  - watch
  - get
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - prow-sinker-leaderlock
  resources:
  - leases
  verbs:
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - prow-sinker-leaderlock
  resources:
  - configmaps
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
