apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sinker
  namespace: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sinker
subjects:
- kind: ServiceAccount
  name: sinker
