apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: statusreconciler
  name: statusreconciler
  namespace: prow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: statusreconciler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: statusreconciler
    spec:
      containers:
      - args:
        - --dry-run=false
        - --continue-on-error=true
        - --plugin-config=/etc/plugins/plugins.yaml
        - --config-path=/etc/config/config.yaml
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --s3-credentials-file=/etc/s3-credentials/service-account.json
        - --status-path=s3://status-reconciler/status-reconciler-status
        - --github-app-id=$(GITHUB_APP_ID)
        - --github-app-private-key-path=/etc/github/cert
        env:
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              key: appid
              name: exe-prow-github-app-github-token
        image: gcr.io/k8s-prow/status-reconciler:v20220818-6dcd812eb2
        imagePullPolicy: IfNotPresent
        name: statusreconciler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/github
          name: github-token
          readOnly: true
        - mountPath: /etc/config
          name: config
          readOnly: true
        - mountPath: /etc/plugins
          name: plugins
          readOnly: true
        - mountPath: /etc/s3-credentials
          name: s3-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: statusreconciler
      serviceAccountName: statusreconciler
      terminationGracePeriodSeconds: 180
      volumes:
      - name: github-token
        secret:
          defaultMode: 420
          secretName: exe-prow-github-app-github-token
      - configMap:
          defaultMode: 420
          name: exe-prow-github-app-config
        name: config
      - configMap:
          defaultMode: 420
          name: exe-prow-github-app-plugins
        name: plugins
      - name: s3-credentials
        secret:
          defaultMode: 420
          secretName: exe-prow-github-app-s3-credentials
