apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"tide","namespace":"prow"},"spec":{"ports":[{"port":80,"targetPort":8888}],"selector":{"app":"tide"}}}
  creationTimestamp: "2020-12-10T12:26:11Z"
  name: tide
  namespace: prow
  resourceVersion: "1231191"
  uid: e5974fbc-c6fb-4312-b78d-d2ab4c123b5d
spec:
  clusterIP: 172.30.128.32
  clusterIPs:
  - 172.30.128.32
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: tide
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
