apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tide
  namespace: prow
rules:
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  verbs:
  - create
  - list
  - get
  - watch
